name: Android CI

on:
  push:
    branches: [ masterr ]
  pull_request:
    branches: [ masterr ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build LineFlag
      run: ./gradlew build
